language: node_js

node_js:
  - "0.10"
  - "0.12"
  - iojs
  - "4"
  - "5"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: "npm test && npm run lint"

after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage