language: node_js

node_js:
  - "0.10"
  - "0.12"
  - iojs
  - "4"
  - "5"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: "npm test && npm run lint"

after_script: 
  - ./node_modules/karma/bin/karma start
  - istanbul cover ./node_modules/mocha/bin/_mocha app/**/*.test.jsx
  - cat ./coverage/lcov.info ./coverage/karma/**/*.info > lcov.info 
  - node node_modules/lcov-filter/index.js lcov.info config | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage