language: node_js

node_js:
  - "0.10"
  - "0.12"
  - iojs
  - "4"
  - "5"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: "npm test && npm run lint"

after_script: 
  - nyc --extension .jsx --extension .es6 npm test && nyc report --reporter=text-lcov | coveralls